/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export declare namespace BuyMeACoffe {
  export type MemoStruct = {
    from: PromiseOrValue<string>;
    timestamp: PromiseOrValue<BigNumberish>;
    name: PromiseOrValue<string>;
    message: PromiseOrValue<string>;
  };

  export type MemoStructOutput = [string, BigNumber, string, string] & {
    from: string;
    timestamp: BigNumber;
    name: string;
    message: string;
  };
}

export interface BuyMeACoffeInterface extends utils.Interface {
  functions: {
    "buyCoffe(string,string)": FunctionFragment;
    "getMemos()": FunctionFragment;
    "withdrawTips()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "buyCoffe" | "getMemos" | "withdrawTips"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "buyCoffe",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "getMemos", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawTips",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "buyCoffe", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getMemos", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawTips",
    data: BytesLike
  ): Result;

  events: {
    "NewMemo(address,uint256,string,string)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "NewMemo"): EventFragment;
}

export interface NewMemoEventObject {
  from: string;
  timestamp: BigNumber;
  name: string;
  message: string;
}
export type NewMemoEvent = TypedEvent<
  [string, BigNumber, string, string],
  NewMemoEventObject
>;

export type NewMemoEventFilter = TypedEventFilter<NewMemoEvent>;

export interface BuyMeACoffe extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: BuyMeACoffeInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    buyCoffe(
      _name: PromiseOrValue<string>,
      _message: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getMemos(
      overrides?: CallOverrides
    ): Promise<[BuyMeACoffe.MemoStructOutput[]]>;

    withdrawTips(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  buyCoffe(
    _name: PromiseOrValue<string>,
    _message: PromiseOrValue<string>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getMemos(overrides?: CallOverrides): Promise<BuyMeACoffe.MemoStructOutput[]>;

  withdrawTips(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    buyCoffe(
      _name: PromiseOrValue<string>,
      _message: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    getMemos(
      overrides?: CallOverrides
    ): Promise<BuyMeACoffe.MemoStructOutput[]>;

    withdrawTips(overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "NewMemo(address,uint256,string,string)"(
      from?: PromiseOrValue<string> | null,
      timestamp?: null,
      name?: null,
      message?: null
    ): NewMemoEventFilter;
    NewMemo(
      from?: PromiseOrValue<string> | null,
      timestamp?: null,
      name?: null,
      message?: null
    ): NewMemoEventFilter;
  };

  estimateGas: {
    buyCoffe(
      _name: PromiseOrValue<string>,
      _message: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getMemos(overrides?: CallOverrides): Promise<BigNumber>;

    withdrawTips(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    buyCoffe(
      _name: PromiseOrValue<string>,
      _message: PromiseOrValue<string>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getMemos(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    withdrawTips(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
